[build]
command = "rm -rf functions && rm .firebaserc && rm firebase.json && rm README.md"


[[redirects]]
from = "/user/*"
to = "/pages/user/index.html"
status = 200

[[redirects]]
from = "/event/*"
to = "/pages/event/index.html"
status = 200

[[redirects]]
from = "/org-guide"
to = "https://docs.google.com/document/d/1NshG1zCRptEe5Mcres3MxNAN-QV2uA5nyyuw4PdcTsE/edit?usp=sharing"
status = 301

[[redirects]]
from = "/"
to = "/pages/"
status = 200

[[redirects]]
from = "/:splat"
to = "/pages/:splat/index.html"
status = 200


